// Regenerate app/lib/abi.ts from the compiled contract artifact.
//
// The frontend ABI is derived from the build output rather than hand-typed, so
// it cannot drift from CurveRacer.sol. The VibeCurve ABI is the surface
// verified by eth_call against a live vibe/vibe curve on Robinhood Chain
// Testnet (chainId 46630) on 2026-09-26.
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const game = require(path.join(root, 'out/CurveRacer.sol/CurveRacer.json')).abi;
const minimal = game.filter((e) => e.type === 'function' || e.type === 'event' || e.type === 'error');

const VIBE_CURVE_ABI = [
  { type: 'function', name: 'graduated', stateMutability: 'view', inputs: [], outputs: [{ type: 'bool' }] },
  { type: 'function', name: 'spotPriceWad', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'virtualEthReserve', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'virtualTokenReserve', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'tokensSoldFromCurve', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'curveTokensRemaining', stateMutability: 'view', inputs: [], outputs: [{ type: 'uint256' }] },
  { type: 'function', name: 'quoteBuyExactTokens', stateMutability: 'view', inputs: [{ name: 'tokens', type: 'uint256' }], outputs: [{ type: 'uint256' }] },
  // topic0 0x654e1d49..., recovered from real curve logs at the graduation
  // block; data word0 = netRaisedWei, word1 = completedAt.
  { type: 'event', name: 'CurveCompleted', inputs: [
    { indexed: false, name: 'netRaisedWei', type: 'uint256' },
    { indexed: false, name: 'completedAt', type: 'uint256' },
  ] },
];

const out = path.join(root, 'app/lib/abi.ts');
fs.writeFileSync(
  out,
  '// AUTO-GENERATED by script/gen-abi.js — do not hand-edit.\n' +
  '// Run: node script/gen-abi.js\n\n' +
  'export const CURVE_RACER_ABI = ' + JSON.stringify(minimal, null, 2) + ' as const;\n\n' +
  '// vibe/vibe bonding-curve surface, verified on-chain 2026-09-26.\n' +
  'export const VIBE_CURVE_ABI = ' + JSON.stringify(VIBE_CURVE_ABI, null, 2) + ' as const;\n'
);
console.log('wrote', out);
console.log('  CURVE_RACER_ABI:', minimal.length, 'entries');
console.log('  VIBE_CURVE_ABI  :', VIBE_CURVE_ABI.length, 'entries');
